resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- literals:
  - PROTECTED_MANAGEMENT_LABELS_DOMAINS=kubernetes.io,openshift.io
  name: controller-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: localhost/meytarzeevi/namespacelabel
  newTag: v0.10

configMapGenerator:
- literals:
  - PROTECTED_MANAGEMENT_LABELS_DOMAINS=kubernetes.io,openshift.io
  name: controller-config

vars:
- fieldref:
    fieldPath: data.PROTECTED_MANAGEMENT_LABELS_DOMAINS
  name: PROTECTED_MANAGEMENT_LABELS_DOMAINS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: controller-config