# permissions for end users to edit namespacelabelconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacelabelconfig-editor-role
rules:
- apiGroups:
  - config.dana.io
  resources:
  - namespacelabelconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.dana.io
  resources:
  - namespacelabelconfigs/status
  verbs:
  - get
