# permissions for end users to edit namespacelabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacelabel-editor-role
rules:
- apiGroups:
  - dana.io.dana.io
  resources:
  - namespacelabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dana.io.dana.io
  resources:
  - namespacelabels/status
  verbs:
  - get
