# permissions for end users to view namespacelabelconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacelabelconfig-viewer-role
rules:
- apiGroups:
  - dana.io.dana.io
  resources:
  - namespacelabelconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dana.io.dana.io
  resources:
  - namespacelabelconfigs/status
  verbs:
  - get
