# permissions for end users to view namespacelabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacelabel-viewer-role
rules:
- apiGroups:
  - dana.io.dana.io
  resources:
  - namespacelabels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dana.io.dana.io
  resources:
  - namespacelabels/status
  verbs:
  - get
