generatorOptions:
  disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: controller-config
  literals:
  - MANAGEMENT_LABELS_DOMAINS=kubernetes.io,openshift.io