name: namespaceLabel Controller workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test_controller:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    
    - name: run make (fmt, vet, build)
      run: make
    
    - name: test controller
      run: make test
